language: go

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/tsenart/deadcode

script:
  - go vet
  - golint
  - deadcode
  - $HOME/gopath/bin/goveralls -v -service=travis-ci

go:
  - 1.8
  - 1.9
